//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.NShape.WinFormsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dataweb.NShape.WinFormsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActivateDesign {
            get {
                object obj = ResourceManager.GetObject("ActivateDesign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddToLayer {
            get {
                object obj = ResourceManager.GetObject("AddToLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AggregateShapeBtn {
            get {
                object obj = ResourceManager.GetObject("AggregateShapeBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AssignToLayer {
            get {
                object obj = ResourceManager.GetObject("AssignToLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all shapes based on template &apos;{0}&apos;.
        /// </summary>
        internal static string CaptionFmt_SelectAllShapesBasedOnTemplate0 {
            get {
                return ResourceManager.GetString("CaptionFmt_SelectAllShapesBasedOnTemplate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all shapes of type &apos;{0}&apos;.
        /// </summary>
        internal static string CaptionFmt_SelectAllShapesOfType0 {
            get {
                return ResourceManager.GetString("CaptionFmt_SelectAllShapesOfType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add shapes to active layers.
        /// </summary>
        internal static string CaptionTxt_AddShapesToActiveLayers {
            get {
                return ResourceManager.GetString("CaptionTxt_AddShapesToActiveLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Shapes.
        /// </summary>
        internal static string CaptionTxt_AggregateShapes {
            get {
                return ResourceManager.GetString("CaptionTxt_AggregateShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign shapes to active layers.
        /// </summary>
        internal static string CaptionTxt_AssignShapesToActiveLayers {
            get {
                return ResourceManager.GetString("CaptionTxt_AssignShapesToActiveLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        internal static string CaptionTxt_BringToFront {
            get {
                return ResourceManager.GetString("CaptionTxt_BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CaptionTxt_Copy {
            get {
                return ResourceManager.GetString("CaptionTxt_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as Image.
        /// </summary>
        internal static string CaptionTxt_CopyAsImage {
            get {
                return ResourceManager.GetString("CaptionTxt_CopyAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CaptionTxt_Cut {
            get {
                return ResourceManager.GetString("CaptionTxt_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CaptionTxt_Delete {
            get {
                return ResourceManager.GetString("CaptionTxt_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disaggregate Shapes.
        /// </summary>
        internal static string CaptionTxt_DisaggregateShapes {
            get {
                return ResourceManager.GetString("CaptionTxt_DisaggregateShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        internal static string CaptionTxt_GroupSelect {
            get {
                return ResourceManager.GetString("CaptionTxt_GroupSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Shapes.
        /// </summary>
        internal static string CaptionTxt_GroupShapes {
            get {
                return ResourceManager.GetString("CaptionTxt_GroupShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string CaptionTxt_Paste {
            get {
                return ResourceManager.GetString("CaptionTxt_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string CaptionTxt_Properties {
            get {
                return ResourceManager.GetString("CaptionTxt_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string CaptionTxt_Redo {
            get {
                return ResourceManager.GetString("CaptionTxt_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shapes from all layers.
        /// </summary>
        internal static string CaptionTxt_RemoveShapesFromAllLayers {
            get {
                return ResourceManager.GetString("CaptionTxt_RemoveShapesFromAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string CaptionTxt_SelectAll {
            get {
                return ResourceManager.GetString("CaptionTxt_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all shapes based on a template.
        /// </summary>
        internal static string CaptionTxt_SelectAllShapesBasedOnATemplate {
            get {
                return ResourceManager.GetString("CaptionTxt_SelectAllShapesBasedOnATemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all shapes of a type.
        /// </summary>
        internal static string CaptionTxt_SelectAllShapesOfAType {
            get {
                return ResourceManager.GetString("CaptionTxt_SelectAllShapesOfAType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        internal static string CaptionTxt_SendToBack {
            get {
                return ResourceManager.GetString("CaptionTxt_SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Info.
        /// </summary>
        internal static string CaptionTxt_ShapeInfo {
            get {
                return ResourceManager.GetString("CaptionTxt_ShapeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string CaptionTxt_Undo {
            get {
                return ResourceManager.GetString("CaptionTxt_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup Shapes.
        /// </summary>
        internal static string CaptionTxt_UngroupShapes {
            get {
                return ResourceManager.GetString("CaptionTxt_UngroupShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all.
        /// </summary>
        internal static string CaptionTxt_UnselectAll {
            get {
                return ResourceManager.GetString("CaptionTxt_UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checked {
            get {
                object obj = ResourceManager.GetObject("Checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyAsImage {
            get {
                object obj = ResourceManager.GetObject("CopyAsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyBtn {
            get {
                object obj = ResourceManager.GetObject("CopyBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyDiagram {
            get {
                object obj = ResourceManager.GetObject("CopyDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CutBtn {
            get {
                object obj = ResourceManager.GetObject("CutBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteBtn {
            get {
                object obj = ResourceManager.GetObject("DeleteBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiagramPropertiesBtn3 {
            get {
                object obj = ResourceManager.GetObject("DiagramPropertiesBtn3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Disabled {
            get {
                object obj = ResourceManager.GetObject("Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Enabled {
            get {
                object obj = ResourceManager.GetObject("Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupBtn {
            get {
                object obj = ResourceManager.GetObject("GroupBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Invisible {
            get {
                object obj = ResourceManager.GetObject("Invisible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Layers {
            get {
                object obj = ResourceManager.GetObject("Layers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModelObjectAttached {
            get {
                object obj = ResourceManager.GetObject("ModelObjectAttached", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModelObjectDetached {
            get {
                object obj = ResourceManager.GetObject("ModelObjectDetached", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewBtn {
            get {
                object obj = ResourceManager.GetObject("NewBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewItemsBtn {
            get {
                object obj = ResourceManager.GetObject("NewItemsBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewLayer {
            get {
                object obj = ResourceManager.GetObject("NewLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PasteBtn {
            get {
                object obj = ResourceManager.GetObject("PasteBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedoBtn {
            get {
                object obj = ResourceManager.GetObject("RedoBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveFromAllLayers {
            get {
                object obj = ResourceManager.GetObject("RemoveFromAllLayers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RenameBtn {
            get {
                object obj = ResourceManager.GetObject("RenameBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplitShapeAggregationBtn {
            get {
                object obj = ResourceManager.GetObject("SplitShapeAggregationBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToBackground {
            get {
                object obj = ResourceManager.GetObject("ToBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToForeground {
            get {
                object obj = ResourceManager.GetObject("ToForeground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} shapes to {1}..
        /// </summary>
        internal static string TooltipFmt_Add0ShapesToLayer1 {
            get {
                return ResourceManager.GetString("TooltipFmt_Add0ShapesToLayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} to {1}..
        /// </summary>
        internal static string TooltipFmt_AddShape0ToLayer1 {
            get {
                return ResourceManager.GetString("TooltipFmt_AddShape0ToLayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate {0} shapes as composite shape..
        /// </summary>
        internal static string TooltipFmt_Aggregate0ShapesAsCompositeShape {
            get {
                return ResourceManager.GetString("TooltipFmt_Aggregate0ShapesAsCompositeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign {0} shapes to {1}..
        /// </summary>
        internal static string TooltipFmt_Assign0ShapesToLayer1 {
            get {
                return ResourceManager.GetString("TooltipFmt_Assign0ShapesToLayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign {0} shape to {1}..
        /// </summary>
        internal static string TooltipFmt_AssignShape0ToLayer1 {
            get {
                return ResourceManager.GetString("TooltipFmt_AssignShape0ToLayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring {0} shapes to foreground..
        /// </summary>
        internal static string TooltipFmt_Bring0ShapesToFront {
            get {
                return ResourceManager.GetString("TooltipFmt_Bring0ShapesToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring {0} shape to foreground..
        /// </summary>
        internal static string TooltipFmt_Bring0ToFront {
            get {
                return ResourceManager.GetString("TooltipFmt_Bring0ToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} shapes..
        /// </summary>
        internal static string TooltipFmt_Copy0Shapes {
            get {
                return ResourceManager.GetString("TooltipFmt_Copy0Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} shape..
        /// </summary>
        internal static string TooltipFmt_CopyShape0 {
            get {
                return ResourceManager.GetString("TooltipFmt_CopyShape0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut {0} shapes..
        /// </summary>
        internal static string TooltipFmt_Cut0Shapes {
            get {
                return ResourceManager.GetString("TooltipFmt_Cut0Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut {0} shape..
        /// </summary>
        internal static string TooltipFmt_CutShape0 {
            get {
                return ResourceManager.GetString("TooltipFmt_CutShape0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} shapes..
        /// </summary>
        internal static string TooltipFmt_Delete0Shapes {
            get {
                return ResourceManager.GetString("TooltipFmt_Delete0Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} shape..
        /// </summary>
        internal static string TooltipFmt_DeleteShape0 {
            get {
                return ResourceManager.GetString("TooltipFmt_DeleteShape0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} shapes..
        /// </summary>
        internal static string TooltipFmt_Group0Shapes {
            get {
                return ResourceManager.GetString("TooltipFmt_Group0Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer {0}.
        /// </summary>
        internal static string TooltipFmt_LayerByName {
            get {
                return ResourceManager.GetString("TooltipFmt_LayerByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layers {0}.
        /// </summary>
        internal static string TooltipFmt_LayersByName {
            get {
                return ResourceManager.GetString("TooltipFmt_LayersByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one shape selected..
        /// </summary>
        internal static string TooltipFmt_MoreThan1ShapeSelected {
            get {
                return ResourceManager.GetString("TooltipFmt_MoreThan1ShapeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} layers.
        /// </summary>
        internal static string TooltipFmt_NumberOfLayers {
            get {
                return ResourceManager.GetString("TooltipFmt_NumberOfLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste {0} shapes..
        /// </summary>
        internal static string TooltipFmt_Paste0Shapes {
            get {
                return ResourceManager.GetString("TooltipFmt_Paste0Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste {0} shape..
        /// </summary>
        internal static string TooltipFmt_PasteShape0 {
            get {
                return ResourceManager.GetString("TooltipFmt_PasteShape0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission &apos;{0}&apos; is not granted..
        /// </summary>
        internal static string TooltipFmt_Permission0IsNotGranted {
            get {
                return ResourceManager.GetString("TooltipFmt_Permission0IsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} shapes from all layers..
        /// </summary>
        internal static string TooltipFmt_Remove0ShapesFromAllLayers {
            get {
                return ResourceManager.GetString("TooltipFmt_Remove0ShapesFromAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} shape from all layers..
        /// </summary>
        internal static string TooltipFmt_RemoveShape0FromAllLayers {
            get {
                return ResourceManager.GetString("TooltipFmt_RemoveShape0FromAllLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all shapes of the diagram based on template &apos;{0}&apos;..
        /// </summary>
        internal static string TooltipFmt_SelectAllShapesOfTheDiagramBasedOnTemplate0 {
            get {
                return ResourceManager.GetString("TooltipFmt_SelectAllShapesOfTheDiagramBasedOnTemplate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all shapes of type &apos;{0}&apos; in the diagram..
        /// </summary>
        internal static string TooltipFmt_SelectAllShapesOfType0InTheDiagram {
            get {
                return ResourceManager.GetString("TooltipFmt_SelectAllShapesOfType0InTheDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send {0} shapes to background..
        /// </summary>
        internal static string TooltipFmt_Send0ShapesToBackground {
            get {
                return ResourceManager.GetString("TooltipFmt_Send0ShapesToBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send {0} shape to background..
        /// </summary>
        internal static string TooltipFmt_Send0ToBackground {
            get {
                return ResourceManager.GetString("TooltipFmt_Send0ToBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes not assigned to layers..
        /// </summary>
        internal static string TooltipFmt_ShapesNotAssignedToLayers {
            get {
                return ResourceManager.GetString("TooltipFmt_ShapesNotAssignedToLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show information for {0} &apos;{1}&apos; .
        /// </summary>
        internal static string TooltipFmt_ShowInformationFor01 {
            get {
                return ResourceManager.GetString("TooltipFmt_ShowInformationFor01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show properties of {0} shapes..
        /// </summary>
        internal static string TooltipFmt_ShowPropertiesOf0Shapes {
            get {
                return ResourceManager.GetString("TooltipFmt_ShowPropertiesOf0Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show properties of diagram &apos;{0}&apos;..
        /// </summary>
        internal static string TooltipFmt_ShowPropertiesOfDiagram0 {
            get {
                return ResourceManager.GetString("TooltipFmt_ShowPropertiesOfDiagram0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show properties of {0} shape..
        /// </summary>
        internal static string TooltipFmt_ShowPropertiesOfShape0 {
            get {
                return ResourceManager.GetString("TooltipFmt_ShowPropertiesOfShape0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup {0} shapes..
        /// </summary>
        internal static string TooltipFmt_Ungroup0Shapes {
            get {
                return ResourceManager.GetString("TooltipFmt_Ungroup0Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All shapes of the diagram are selected..
        /// </summary>
        internal static string TooltipTxt_AllShapesOfTheDiagramAreSelected {
            get {
                return ResourceManager.GetString("TooltipTxt_AllShapesOfTheDiagramAreSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy diagram as PNG and EMF image to clipboard..
        /// </summary>
        internal static string TooltipTxt_CopyDiagramAsPNGAndEMFImageToClipboard {
            get {
                return ResourceManager.GetString("TooltipTxt_CopyDiagramAsPNGAndEMFImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected shapes as PNG and EMF image to clipboard..
        /// </summary>
        internal static string TooltipTxt_CopySelectionAsPNGAndEMFImageToClipboard {
            get {
                return ResourceManager.GetString("TooltipTxt_CopySelectionAsPNGAndEMFImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disaggregate the selected shape aggregation..
        /// </summary>
        internal static string TooltipTxt_DisaggregateTheSelectedShapeAggregation {
            get {
                return ResourceManager.GetString("TooltipTxt_DisaggregateTheSelectedShapeAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or unselect shapes..
        /// </summary>
        internal static string TooltipTxt_GroupSelect {
            get {
                return ResourceManager.GetString("TooltipTxt_GroupSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear shapes may not be the base for a composite shape..
        /// </summary>
        internal static string TooltipTxt_LinearShapesMayNotBeTheBaseForACompositeShape {
            get {
                return ResourceManager.GetString("TooltipTxt_LinearShapesMayNotBeTheBaseForACompositeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group selected..
        /// </summary>
        internal static string TooltipTxt_NoGroupSelected {
            get {
                return ResourceManager.GetString("TooltipTxt_NoGroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layers active..
        /// </summary>
        internal static string TooltipTxt_NoLayersActive {
            get {
                return ResourceManager.GetString("TooltipTxt_NoLayersActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No redo commands left..
        /// </summary>
        internal static string TooltipTxt_NoRedoCommandsLeft {
            get {
                return ResourceManager.GetString("TooltipTxt_NoRedoCommandsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shapes cut/copied yet..
        /// </summary>
        internal static string TooltipTxt_NoShapesCutCopiedYet {
            get {
                return ResourceManager.GetString("TooltipTxt_NoShapesCutCopiedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shapes selected..
        /// </summary>
        internal static string TooltipTxt_NoShapesSelected {
            get {
                return ResourceManager.GetString("TooltipTxt_NoShapesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shape under the mouse cursor..
        /// </summary>
        internal static string TooltipTxt_NoShapeUnderTheMouseCursor {
            get {
                return ResourceManager.GetString("TooltipTxt_NoShapeUnderTheMouseCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough shapes selected..
        /// </summary>
        internal static string TooltipTxt_NotEnoughShapesSelected {
            get {
                return ResourceManager.GetString("TooltipTxt_NotEnoughShapesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No undo commands left..
        /// </summary>
        internal static string TooltipTxt_NoUndoCommandsLeft {
            get {
                return ResourceManager.GetString("TooltipTxt_NoUndoCommandsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties are not available..
        /// </summary>
        internal static string TooltipTxt_PropertiesAreNotAvailable {
            get {
                return ResourceManager.GetString("TooltipTxt_PropertiesAreNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all shapes of the diagram..
        /// </summary>
        internal static string TooltipTxt_SelectAllShapesOfTheDiagram {
            get {
                return ResourceManager.GetString("TooltipTxt_SelectAllShapesOfTheDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected shape is not a composite shape..
        /// </summary>
        internal static string TooltipTxt_SelectedShapeIsNotACompositeShape {
            get {
                return ResourceManager.GetString("TooltipTxt_SelectedShapeIsNotACompositeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are shapes assigned to the model(s)..
        /// </summary>
        internal static string TooltipTxt_ThereAreShapesAssignedToTheModelObjects {
            get {
                return ResourceManager.GetString("TooltipTxt_ThereAreShapesAssignedToTheModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected group is member of another group..
        /// </summary>
        internal static string TooltipTxt_TheSelectedGroupIsMemberOfAnotherGroup {
            get {
                return ResourceManager.GetString("TooltipTxt_TheSelectedGroupIsMemberOfAnotherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shape under the cursor is not based on any template..
        /// </summary>
        internal static string TooltipTxt_TheShapeUnderTheCursorIsNotBasedOnAnyTemplate {
            get {
                return ResourceManager.GetString("TooltipTxt_TheShapeUnderTheCursorIsNotBasedOnAnyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many shapes selected..
        /// </summary>
        internal static string TooltipTxt_TooManyShapesSelected {
            get {
                return ResourceManager.GetString("TooltipTxt_TooManyShapesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all selected shapes..
        /// </summary>
        internal static string TooltipTxt_UnselectAllSelectedShapes {
            get {
                return ResourceManager.GetString("TooltipTxt_UnselectAllSelectedShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Models.
        /// </summary>
        internal static string TooltipTxt_WithModelsPostfix {
            get {
                return ResourceManager.GetString("TooltipTxt_WithModelsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unchecked {
            get {
                object obj = ResourceManager.GetObject("Unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UndoBtn {
            get {
                object obj = ResourceManager.GetObject("UndoBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UngroupBtn {
            get {
                object obj = ResourceManager.GetObject("UngroupBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Visible {
            get {
                object obj = ResourceManager.GetObject("Visible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
