//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.NShape.GeneralShapes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dataweb.NShape.GeneralShapes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BitmapShapeIconLarge {
            get {
                object obj = ResourceManager.GetObject("BitmapShapeIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BitmapShapeIconSmall {
            get {
                object obj = ResourceManager.GetObject("BitmapShapeIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property EndCapStyle is not set..
        /// </summary>
        internal static string MessageTxt_PropertyEndCapStyleIsNotSet {
            get {
                return ResourceManager.GetString("MessageTxt_PropertyEndCapStyleIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property StartCapStyle is not set..
        /// </summary>
        internal static string MessageTxt_PropertyStartCapStyleIsNotSet {
            get {
                return ResourceManager.GetString("MessageTxt_PropertyStartCapStyleIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the line cap appearance of the line&apos;s ending.\nUse the template editor to modify all shapes of a template.\nUse the design editor to modify and create styles..
        /// </summary>
        internal static string PropDesc_Line_EndCapStyle {
            get {
                return ResourceManager.GetString("PropDesc_Line_EndCapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the line cap appearance of the line&apos;s beginning.\nUse the template editor to modify all shapes of a template.\nUse the design editor to modify and create styles..
        /// </summary>
        internal static string PropDesc_Line_StartCapStyle {
            get {
                return ResourceManager.GetString("PropDesc_Line_StartCapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the arrow&apos;s body..
        /// </summary>
        internal static string PropDesc_ThickArrow_BodyHeight {
            get {
                return ResourceManager.GetString("PropDesc_ThickArrow_BodyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the arrow&apos;s tip..
        /// </summary>
        internal static string PropDesc_ThickArrow_HeadWidth {
            get {
                return ResourceManager.GetString("PropDesc_ThickArrow_HeadWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Cap Style.
        /// </summary>
        internal static string PropName_Line_EndCapStyle {
            get {
                return ResourceManager.GetString("PropName_Line_EndCapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cap Style.
        /// </summary>
        internal static string PropName_Line_StartCapStyle {
            get {
                return ResourceManager.GetString("PropName_Line_StartCapStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Height.
        /// </summary>
        internal static string PropName_ThickArrow_BodyHeight {
            get {
                return ResourceManager.GetString("PropName_ThickArrow_BodyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Width.
        /// </summary>
        internal static string PropName_ThickArrow_HeadWidth {
            get {
                return ResourceManager.GetString("PropName_ThickArrow_HeadWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShaperReferenceCircle {
            get {
                object obj = ResourceManager.GetObject("ShaperReferenceCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShaperReferenceDiamond {
            get {
                object obj = ResourceManager.GetObject("ShaperReferenceDiamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShaperReferenceQuadrangle {
            get {
                object obj = ResourceManager.GetObject("ShaperReferenceQuadrangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShaperReferenceTriangle {
            get {
                object obj = ResourceManager.GetObject("ShaperReferenceTriangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
