//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.NShape.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dataweb.NShape.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ActionDeniedCursor {
            get {
                object obj = ResourceManager.GetObject("ActionDeniedCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AggregateShapeBtn {
            get {
                object obj = ResourceManager.GetObject("AggregateShapeBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate {0}.
        /// </summary>
        internal static string CaptionFmt_Activate0 {
            get {
                return ResourceManager.GetString("CaptionFmt_Activate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate {0}.
        /// </summary>
        internal static string CaptionFmt_Deactivate0 {
            get {
                return ResourceManager.GetString("CaptionFmt_Deactivate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0}.
        /// </summary>
        internal static string CaptionFmt_Hide0 {
            get {
                return ResourceManager.GetString("CaptionFmt_Hide0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0}.
        /// </summary>
        internal static string CaptionFmt_Show0 {
            get {
                return ResourceManager.GetString("CaptionFmt_Show0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Layer.
        /// </summary>
        internal static string CaptionTxt_AddLayer {
            get {
                return ResourceManager.GetString("CaptionTxt_AddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CaptionTxt_Copy {
            get {
                return ResourceManager.GetString("CaptionTxt_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template.
        /// </summary>
        internal static string CaptionTxt_CreateTemplate {
            get {
                return ResourceManager.GetString("CaptionTxt_CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CaptionTxt_Delete {
            get {
                return ResourceManager.GetString("CaptionTxt_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Layer.
        /// </summary>
        internal static string CaptionTxt_DeleteLayer {
            get {
                return ResourceManager.GetString("CaptionTxt_DeleteLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Layers.
        /// </summary>
        internal static string CaptionTxt_DeleteLayers {
            get {
                return ResourceManager.GetString("CaptionTxt_DeleteLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Template....
        /// </summary>
        internal static string CaptionTxt_DeleteTemplate {
            get {
                return ResourceManager.GetString("CaptionTxt_DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template....
        /// </summary>
        internal static string CaptionTxt_EditTemplate {
            get {
                return ResourceManager.GetString("CaptionTxt_EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Connection Point.
        /// </summary>
        internal static string CaptionTxt_InsertConnectionPoint {
            get {
                return ResourceManager.GetString("CaptionTxt_InsertConnectionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Point.
        /// </summary>
        internal static string CaptionTxt_InsertPoint {
            get {
                return ResourceManager.GetString("CaptionTxt_InsertPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Vertex.
        /// </summary>
        internal static string CaptionTxt_InsertVertex {
            get {
                return ResourceManager.GetString("CaptionTxt_InsertVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string CaptionTxt_Paste {
            get {
                return ResourceManager.GetString("CaptionTxt_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Connection Point.
        /// </summary>
        internal static string CaptionTxt_RemoveConnectionPoint {
            get {
                return ResourceManager.GetString("CaptionTxt_RemoveConnectionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Point.
        /// </summary>
        internal static string CaptionTxt_RemovePoint {
            get {
                return ResourceManager.GetString("CaptionTxt_RemovePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Vertex.
        /// </summary>
        internal static string CaptionTxt_RemoveVertex {
            get {
                return ResourceManager.GetString("CaptionTxt_RemoveVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Layer.
        /// </summary>
        internal static string CaptionTxt_RenameLayer {
            get {
                return ResourceManager.GetString("CaptionTxt_RenameLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Design Editor....
        /// </summary>
        internal static string CaptionTxt_ShowDesignEditor {
            get {
                return ResourceManager.GetString("CaptionTxt_ShowDesignEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Library Manager....
        /// </summary>
        internal static string CaptionTxt_ShowLibraryManager {
            get {
                return ResourceManager.GetString("CaptionTxt_ShowLibraryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template....
        /// </summary>
        internal static string CaptjonTxt_CreateTemplateWithDialog {
            get {
                return ResourceManager.GetString("CaptjonTxt_CreateTemplateWithDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyBtn {
            get {
                object obj = ResourceManager.GetObject("CopyBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CrossCursor {
            get {
                object obj = ResourceManager.GetObject("CrossCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CutBtn {
            get {
                object obj = ResourceManager.GetObject("CutBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultBitmapLarge {
            get {
                object obj = ResourceManager.GetObject("DefaultBitmapLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultBitmapSmall {
            get {
                object obj = ResourceManager.GetObject("DefaultBitmapSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteBtn {
            get {
                object obj = ResourceManager.GetObject("DeleteBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DesignEditorBtn {
            get {
                object obj = ResourceManager.GetObject("DesignEditorBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiagramPropertiesBtn {
            get {
                object obj = ResourceManager.GetObject("DiagramPropertiesBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Disabled {
            get {
                object obj = ResourceManager.GetObject("Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EditTextCursor {
            get {
                object obj = ResourceManager.GetObject("EditTextCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Enabled {
            get {
                object obj = ResourceManager.GetObject("Enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindShapes {
            get {
                object obj = ResourceManager.GetObject("FindShapes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreehandIconLarge {
            get {
                object obj = ResourceManager.GetObject("FreehandIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreehandIconSmall {
            get {
                object obj = ResourceManager.GetObject("FreehandIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupBtn {
            get {
                object obj = ResourceManager.GetObject("GroupBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HandCursor {
            get {
                object obj = ResourceManager.GetObject("HandCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Invisible {
            get {
                object obj = ResourceManager.GetObject("Invisible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LibrariesBtn {
            get {
                object obj = ResourceManager.GetObject("LibrariesBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LockIcon {
            get {
                object obj = ResourceManager.GetObject("LockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate {0} {1}.
        /// </summary>
        internal static string MessageFmt_Activate01 {
            get {
                return ResourceManager.GetString("MessageFmt_Activate01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} model objects..
        /// </summary>
        internal static string MessageFmt_Copy0ModelObjects {
            get {
                return ResourceManager.GetString("MessageFmt_Copy0ModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate {0} {1}.
        /// </summary>
        internal static string MessageFmt_Deactivate01 {
            get {
                return ResourceManager.GetString("MessageFmt_Deactivate01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} layers.
        /// </summary>
        internal static string MessageFmt_Delete0Layers {
            get {
                return ResourceManager.GetString("MessageFmt_Delete0Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} model objects..
        /// </summary>
        internal static string MessageFmt_Delete0ModelObjects {
            get {
                return ResourceManager.GetString("MessageFmt_Delete0ModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete model object.
        /// </summary>
        internal static string MessageFmt_DeleteModelObject {
            get {
                return ResourceManager.GetString("MessageFmt_DeleteModelObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Template &apos;{0}&apos;.
        /// </summary>
        internal static string MessageFmt_DeleteTemplate0 {
            get {
                return ResourceManager.GetString("MessageFmt_DeleteTemplate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template &apos;{0}&apos;.
        /// </summary>
        internal static string MessageFmt_EditTemplate0 {
            get {
                return ResourceManager.GetString("MessageFmt_EditTemplate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0} layer{1}.
        /// </summary>
        internal static string MessageFmt_Hide01 {
            get {
                return ResourceManager.GetString("MessageFmt_Hide01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shapes selected..
        /// </summary>
        internal static string MessageFmt_NoShapesSelected {
            get {
                return ResourceManager.GetString("MessageFmt_NoShapesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shapes to ungroup.
        /// </summary>
        internal static string MessageFmt_NoShapesToUngroup {
            get {
                return ResourceManager.GetString("MessageFmt_NoShapesToUngroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough shapes selected..
        /// </summary>
        internal static string MessageFmt_NotEnoughShapesSelected {
            get {
                return ResourceManager.GetString("MessageFmt_NotEnoughShapesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste {0} model objects..
        /// </summary>
        internal static string MessageFmt_Paste0ModelObjects {
            get {
                return ResourceManager.GetString("MessageFmt_Paste0ModelObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission {0} not granted..
        /// </summary>
        internal static string MessageFmt_Permission0NotGranted {
            get {
                return ResourceManager.GetString("MessageFmt_Permission0NotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename layer &apos;{0}&apos;.
        /// </summary>
        internal static string MessageFmt_RenameLayer0 {
            get {
                return ResourceManager.GetString("MessageFmt_RenameLayer0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} {1}.
        /// </summary>
        internal static string MessageFmt_Show01 {
            get {
                return ResourceManager.GetString("MessageFmt_Show01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{0}&apos; is in use..
        /// </summary>
        internal static string MessageFmt_Template0IsInUse {
            get {
                return ResourceManager.GetString("MessageFmt_Template0IsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new layer to the diagram.
        /// </summary>
        internal static string MessageTxt_AddANewLayerToTheDiagram {
            get {
                return ResourceManager.GetString("MessageTxt_AddANewLayerToTheDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection point is connected.
        /// </summary>
        internal static string MessageTxt_ConnectionPointIsConnected {
            get {
                return ResourceManager.GetString("MessageTxt_ConnectionPointIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control point is connected.
        /// </summary>
        internal static string MessageTxt_ControlPointIsConnected {
            get {
                return ResourceManager.GetString("MessageTxt_ControlPointIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy model object.
        /// </summary>
        internal static string MessageTxt_CopyModelObject {
            get {
                return ResourceManager.GetString("MessageTxt_CopyModelObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new template..
        /// </summary>
        internal static string MessageTxt_CreateANewTemplate {
            get {
                return ResourceManager.GetString("MessageTxt_CreateANewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram already contains at least one of the shapes to be inserted..
        /// </summary>
        internal static string MessageTxt_DiagramAlreadyContainsAtLeastOneOfTheShapesToBeInserted {
            get {
                return ResourceManager.GetString("MessageTxt_DiagramAlreadyContainsAtLeastOneOfTheShapesToBeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the current design or create new designs.
        /// </summary>
        internal static string MessageTxt_EditTheCurrentDesignOrCreateNewDesigns {
            get {
                return ResourceManager.GetString("MessageTxt_EditTheCurrentDesignOrCreateNewDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and select all assigned shapes..
        /// </summary>
        internal static string MessageTxt_FindAndSelectAllAssignedShapes {
            get {
                return ResourceManager.GetString("MessageTxt_FindAndSelectAllAssignedShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find assigned shapes.
        /// </summary>
        internal static string MessageTxt_FindAssignedShapes {
            get {
                return ResourceManager.GetString("MessageTxt_FindAssignedShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glue control points may not be removed..
        /// </summary>
        internal static string MessageTxt_GlueControlPointsMayNotBeRemoved {
            get {
                return ResourceManager.GetString("MessageTxt_GlueControlPointsMayNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups cannot be aggregated..
        /// </summary>
        internal static string MessageTxt_GroupsCannotBeAggregated {
            get {
                return ResourceManager.GetString("MessageTxt_GroupsCannotBeAggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups cannot be disaggregated..
        /// </summary>
        internal static string MessageTxt_GroupsCannotBeDisaggregated {
            get {
                return ResourceManager.GetString("MessageTxt_GroupsCannotBeDisaggregated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load and unload shape and/or model libraries.
        /// </summary>
        internal static string MessageTxt_LoadAndUnloadShapeAndOrModelLibraries {
            get {
                return ResourceManager.GetString("MessageTxt_LoadAndUnloadShapeAndOrModelLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of layers reached.
        /// </summary>
        internal static string MessageTxt_MaximumNumberOfLayersReached {
            get {
                return ResourceManager.GetString("MessageTxt_MaximumNumberOfLayersReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum vertex count reached.
        /// </summary>
        internal static string MessageTxt_MinimumVertexCountReached {
            get {
                return ResourceManager.GetString("MessageTxt_MinimumVertexCountReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection point was clicked.
        /// </summary>
        internal static string MessageTxt_NoConnectionPointWasClicked {
            get {
                return ResourceManager.GetString("MessageTxt_NoConnectionPointWasClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No control point was clicked.
        /// </summary>
        internal static string MessageTxt_NoControlPointWasClicked {
            get {
                return ResourceManager.GetString("MessageTxt_NoControlPointWasClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layers selected.
        /// </summary>
        internal static string MessageTxt_NoLayersSelected {
            get {
                return ResourceManager.GetString("MessageTxt_NoLayersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model objects copied..
        /// </summary>
        internal static string MessageTxt_NoModelObjectsCopied {
            get {
                return ResourceManager.GetString("MessageTxt_NoModelObjectsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model objects selected.
        /// </summary>
        internal static string MessageTxt_NoModelObjectsSelected {
            get {
                return ResourceManager.GetString("MessageTxt_NoModelObjectsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resize point was clicked.
        /// </summary>
        internal static string MessageTxt_NoResizePointWasClicked {
            get {
                return ResourceManager.GetString("MessageTxt_NoResizePointWasClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shapes cut/copied..
        /// </summary>
        internal static string MessageTxt_NoShapesCutOrCopied {
            get {
                return ResourceManager.GetString("MessageTxt_NoShapesCutOrCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template tool selected.
        /// </summary>
        internal static string MessageTxt_NoTemplateToolSelected {
            get {
                return ResourceManager.GetString("MessageTxt_NoTemplateToolSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more child model objects are attached to shapes..
        /// </summary>
        internal static string MessageTxt_OneOrMoreChildModelObjectsAreAttachedToShapes {
            get {
                return ResourceManager.GetString("MessageTxt_OneOrMoreChildModelObjectsAreAttachedToShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste model object.
        /// </summary>
        internal static string MessageTxt_PasteModelObject {
            get {
                return ResourceManager.GetString("MessageTxt_PasteModelObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape is not a composite shape..
        /// </summary>
        internal static string MessageTxt_ShapeIsNotACompositeShape {
            get {
                return ResourceManager.GetString("MessageTxt_ShapeIsNotACompositeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape is not a group shape..
        /// </summary>
        internal static string MessageTxt_ShapeIsNotAGroupShape {
            get {
                return ResourceManager.GetString("MessageTxt_ShapeIsNotAGroupShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line already has the maximum number of vertices.
        /// </summary>
        internal static string MessageTxt_TheLineAlreadyHasTheMaximumNumberOfVertices {
            get {
                return ResourceManager.GetString("MessageTxt_TheLineAlreadyHasTheMaximumNumberOfVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many layers selected.
        /// </summary>
        internal static string MessageTxt_TooManyLayersSelected {
            get {
                return ResourceManager.GetString("MessageTxt_TooManyLayersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many shapes selected..
        /// </summary>
        internal static string MessageTxt_TooManyShapesSelected {
            get {
                return ResourceManager.GetString("MessageTxt_TooManyShapesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to click on the line in order to insert new points.
        /// </summary>
        internal static string MessageTxt_YouHaveToClickOnTheLineInOrderToInsertNewPoints {
            get {
                return ResourceManager.GetString("MessageTxt_YouHaveToClickOnTheLineInOrderToInsertNewPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MovePointCursor {
            get {
                object obj = ResourceManager.GetObject("MovePointCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MoveShapeCursor {
            get {
                object obj = ResourceManager.GetObject("MoveShapeCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewLayer {
            get {
                object obj = ResourceManager.GetObject("NewLayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PasteBtn {
            get {
                object obj = ResourceManager.GetObject("PasteBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PenCursor {
            get {
                object obj = ResourceManager.GetObject("PenCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PenPlusCursor {
            get {
                object obj = ResourceManager.GetObject("PenPlusCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointerIconLarge {
            get {
                object obj = ResourceManager.GetObject("PointerIconLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointerIconSmall {
            get {
                object obj = ResourceManager.GetObject("PointerIconSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedoBtn {
            get {
                object obj = ResourceManager.GetObject("RedoBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RenameBtn {
            get {
                object obj = ResourceManager.GetObject("RenameBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RotateCursor {
            get {
                object obj = ResourceManager.GetObject("RotateCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplitShapeAggregationBtn {
            get {
                object obj = ResourceManager.GetObject("SplitShapeAggregationBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Text_CategoryGeneral {
            get {
                return ResourceManager.GetString("Text_CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer.
        /// </summary>
        internal static string Text_Layer {
            get {
                return ResourceManager.GetString("Text_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layers.
        /// </summary>
        internal static string Text_Layers {
            get {
                return ResourceManager.GetString("Text_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToBackground {
            get {
                object obj = ResourceManager.GetObject("ToBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToForeground {
            get {
                object obj = ResourceManager.GetObject("ToForeground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UndoBtn {
            get {
                object obj = ResourceManager.GetObject("UndoBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UngroupBtn {
            get {
                object obj = ResourceManager.GetObject("UngroupBtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnlockIcon {
            get {
                object obj = ResourceManager.GetObject("UnlockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Visible {
            get {
                object obj = ResourceManager.GetObject("Visible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
