//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataweb.NShape.SoftwareArchitectureShapes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dataweb.NShape.SoftwareArchitectureShapes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Actor {
            get {
                object obj = ResourceManager.GetObject("Actor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Column.
        /// </summary>
        internal static string CaptionTxt__AppendColumn {
            get {
                return ResourceManager.GetString("CaptionTxt__AppendColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Column.
        /// </summary>
        internal static string CaptionTxt_InsertColumn {
            get {
                return ResourceManager.GetString("CaptionTxt_InsertColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Column.
        /// </summary>
        internal static string CaptionTxt_RemoveColumn {
            get {
                return ResourceManager.GetString("CaptionTxt_RemoveColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Desktop {
            get {
                object obj = ResourceManager.GetObject("Desktop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Laptop {
            get {
                object obj = ResourceManager.GetObject("Laptop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new column before column &apos;{0}&apos;.
        /// </summary>
        internal static string MessageFmt_InsertNewColumnBeforeColumn0 {
            get {
                return ResourceManager.GetString("MessageFmt_InsertNewColumnBeforeColumn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove column &apos;{0}&apos;.
        /// </summary>
        internal static string MessageFmt_RemoveColumn0 {
            get {
                return ResourceManager.GetString("MessageFmt_RemoveColumn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No caption clicked..
        /// </summary>
        internal static string MessageTxt_NoCaptionClicked {
            get {
                return ResourceManager.GetString("MessageTxt_NoCaptionClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Monitor {
            get {
                object obj = ResourceManager.GetObject("Monitor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RTU {
            get {
                object obj = ResourceManager.GetObject("RTU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Tower {
            get {
                object obj = ResourceManager.GetObject("Tower", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
